apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: xva-batch-controller-svc
  name: myxva-batch-controller-svc
spec:
  ports:
  - name: 8089-8080
    port: 8089
    protocol: TCP
    targetPort: 8080
  selector:
    app: xva-batch-controller-api
  type: LoadBalancer
status:
  loadBalancer: {}
